name: Build Bootloader for CLT-R30B1

on:
  workflow_dispatch:
   inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/hanwckf/bl-mt798x
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y gcc-aarch64-linux-gnu build-essential flex bison libssl-dev
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 bootloader
        ln -sf /workdir/bootloader $GITHUB_WORKSPACE/bootloader

    - name: SSH connect to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true') || contains(github.event.action, 'ssh')

    - name: Compile the bootloader
      run: |
        chmod -R 755 bootloader
        cd bootloader
        SOC=mt7981 BOARD=clt_r30b1 MULTI_LAYOUT=1 ./build.sh
        echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV
        echo "compile_status=success" >> $GITHUB_ENV

    - name: Upload bootloader to release
      uses: softprops/action-gh-release@master
      if: ${{ env.compile_status == 'success' }} && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Bootloader_CLT-R30B1_${{ env.FILE_DATE }}
        files: bootloader/output/*.bin

    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 1
        delete_tags : true
        delete_tag_pattern : Bootloader